version: 1.0.0
min_ruby_version: 2.4.0
name: Dank
description: Taylor Thompson's Blog
url: https://teukka.tech
repository: jamestthompson3/dank
author: taylor thompson

plugins:
  - jekyll-feed

highlighter: rouge
