baseURL = "https://teukka.tech/"
languageCode = "en-us"
title = "teukka.tech"
theme = "archie"
pygmentsstyle = "rrt"
enableRobotsTXT = true

[params]
mode = "auto"
ShowInMainFeed = ["updates", "posts", "photos"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[author]
name = "taylor thompson"
email = "taylor@teukka.tech"

[[params.redirect]]
from = "/feed.xml"
to = "/index.xml"

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "photos"
url = "/photos"
weight = 3

[[menu.main]]
name = "updates"
url = "/updates"
weight = 4

[[menu.main]]
name = "rss feeds"
url = "/feeds"
weight = 5

[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100
