baseURL = "https://teukka.tech/"
languageCode = "en-us"
title = "teukka.tech"
theme = "archie"
pygmentsstyle = "rrt"
enableRobotsTXT = true

[params]
mode = "auto"
ShowInMainFeed = ["updates", "posts"]


[author]
name = "taylor thompson"
email = "taylor@teukka.tech"

[[params.redirect]]
from = "/feed.xml"
to = "/index.xml"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Knowledge Base"
url = "/knowledgebase"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Updates"
url = "/updates"
weight = 2

[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100
