name: Feeds

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Fetch RSS Feeds
        env:
          RSS_TOKEN: ${{ secrets.RSS_TOKEN }}
        run: node ./rssfeeds.js

      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            Fetch webmentions
            skip-checks: true
        run: |
          git config user.email "taylor@teukka.tech"
          git config user.name "RSS Feed Bot"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/jamestthompson3/dank.git
          git checkout master
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
